# The 32 and 64 bit version of these actions should be kept in sync
name: Android 32/64-bit Release

on:
  push:
    branches:
      - 'pr-chcnav-aa450'
      - 'pr-chcnav-aa450-2'

defaults:
  run:
    shell: bash

env:
  SOURCE_DIR:   ${{ github.workspace }}
  QT_VERSION:   6.6.*
  BUILD_TYPE:   ${{ fromJSON('["DailyBuild", "StableBuild"]')[ github.ref_type == 'tag' || contains(github.ref, 'Stable_' ) ] }}

jobs:
  build:
    runs-on:  ubuntu-latest

    strategy:
      matrix:
       include:
         - architecture: 32bits
           eabi: armeabi-v7a
           arch: android_armv7
           ARTIFACT: QGroundControl32.apk

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - run: sudo apt update

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          create-symlink: true
          key: ${{ runner.os }}-${{ matrix.arch }}-Release
          restore-keys: ${{ runner.os }}-${{ matrix.arch }}-Release
          max-size: "2G"
          append-timestamp: false
        if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'

      - name: Get all tags for correct version determination
        working-directory:  ${{ github.workspace }}
        run: |
          git fetch --all --tags -f --depth 1

      - name: Install Qt6 for Android
        uses: jurplel/install-qt-action@v3
        with:
          version:      ${{ env.QT_VERSION }}
          aqtversion:   ==3.1.*
          host:         linux
          target:       android
          arch:         ${{ matrix.arch }}
          extra:        --autodesktop
          dir:          ${{ runner.temp }}
          modules:      qtcharts qtlocation qtpositioning qtspeech qt5compat qtmultimedia qtserialport qtimageformats qtshadertools qtconnectivity qtquick3d
          setup-python: true
          cache: true

      - name: Remove Android SDKs to force usage of android-33 only
        run: |
            ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --uninstall "platforms;android-33-ext5"
            ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --uninstall "platforms;android-33-ext4"
            ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --uninstall "platforms;android-34"
            ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --uninstall "platforms;android-34-ext8"

      - name: Create build directory
        run:  mkdir ${{ runner.temp }}/shadow_build_dir

      - name:               Install gstreamer
        working-directory:  ${{ github.workspace }}
        run: |
            wget --quiet https://gstreamer.freedesktop.org/data/pkg/android/1.18.5/gstreamer-1.0-android-universal-1.18.5.tar.xz
            mkdir gstreamer-1.0-android-universal-1.18.5
            tar xf gstreamer-1.0-android-universal-1.18.5.tar.xz -C gstreamer-1.0-android-universal-1.18.5

      - name: Update android manifest
        if: github.ref_name != 'Stable'
        run: |
            ${SOURCE_DIR}/tools/update_android_manifest_package.sh ${{ github.ref_name }}

      - name: Build
        working-directory: ${{ runner.temp }}/shadow_build_dir
        run:  |
            ls /home/runner/work/_temp/Qt/${{ env.QT_VERSION }}
            qmake -r ${SOURCE_DIR}/qgroundcontrol.pro -spec android-clang CONFIG+=${BUILD_TYPE} CONFIG+=installer ANDROID_ABIS="${{ matrix.eabi }}"
            make -j2

      - name: Upload Build File
        uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.ARTIFACT }}
          path: ${{ runner.temp }}/shadow_build_dir/package/${{ matrix.ARTIFACT }}
